# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://vin136.github.io/fastrl/"

git_url = "https://github.com/vin136/fastrl/tree/master/"

def custom_doc_links(name): return None
